name: PR diff stats

on:
  pull_request:
    types: [opened, synchronize, reopened]

permissions:
  contents: read
  pull-requests: write

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number }}
  cancel-in-progress: true

jobs:
  update_comment:
    runs-on: ubuntu-latest
    timeout-minutes: 5

    steps:
      - name: Update diff comment
        uses: milkstrawai/pr-diff-stats@feat/text-report
        with:
          format: text-chart
